# Generated by Django 4.1.6 on 2023-02-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_pet',
            name='pet',
        ),
    ]
