# Generated by Django 4.1.6 on 2023-02-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_pet_med'),
        ('medical_pet_app', '0002_remove_medical_pet_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_pet',
            name='pet',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='listings.pet'),
            preserve_default=False,
        ),
    ]
