# Generated by Django 4.1.6 on 2023-02-24 07:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_pet_med'),
        ('medical_pet_app', '0003_medical_pet_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_shots', models.IntegerField(blank=True, null=True)),
                ('shot_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('first_shot', models.DateTimeField()),
                ('notification', models.BooleanField(default=False)),
                ('shot_duration', models.IntegerField(blank=True, null=True)),
                ('is_adult', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medical_pet',
            name='med',
        ),
        migrations.AlterField(
            model_name='medical_pet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.pet'),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='med_v',
            field=models.OneToOneField(default=121, on_delete=django.db.models.deletion.CASCADE, to='medical_pet_app.vaccine_pet'),
            preserve_default=False,
        ),
    ]
