# Generated by Django 4.1.6 on 2023-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0004_vaccine_pet_remove_medical_pet_med_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_pet',
            name='med_v',
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='first_shot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='is_adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='shot_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='total_shots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vaccine_pet',
        ),
    ]
