# Generated by Django 4.1.6 on 2023-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0005_remove_medical_pet_med_v_medical_pet_first_shot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_pet',
            name='total_shots',
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='last_shot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
