# Generated by Django 4.1.6 on 2023-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0006_remove_medical_pet_total_shots_medical_pet_last_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_pet',
            name='next_shot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
