# Generated by Django 4.1.6 on 2023-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0007_medical_pet_next_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_pet',
            name='first_shot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_pet',
            name='last_shot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_pet',
            name='next_shot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
