# Generated by Django 4.1.6 on 2023-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0008_alter_medical_pet_first_shot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_pet',
            old_name='first_shot',
            new_name='suggest_shot',
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='dscription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical_pet',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
