# Generated by Django 4.1.6 on 2023-02-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/qr_code/%Y/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth:'),
        ),
    ]
