# Generated by Django 4.1.6 on 2023-02-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_pet_pet_gender_pet_qr_code_img_alter_pet_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='chip_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Chip Number'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True, verbose_name='Gender'),
        ),
    ]
