# Generated by Django 4.1.6 on 2023-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_pet_chip_num_alter_pet_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image1',
            field=models.ImageField(blank=True, default='default_pet.png', null=True, upload_to='pet_images/%Y/'),
        ),
    ]
