# Generated by Django 4.1.6 on 2023-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_pet_pet_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image1',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/%Y/'),
        ),
    ]
