# Generated by Django 4.1.6 on 2023-02-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_pet_pet_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_disc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
