# Generated by Django 4.1.6 on 2023-02-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_pet_pet_color_pet_pet_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='qr_code_img',
        ),
    ]
