# Generated by Django 4.1.6 on 2023-02-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_pet_med'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='med',
        ),
    ]
