# Generated by Django 4.1.6 on 2023-02-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_pet_app', '0002_remove_medical_pet_pet'),
        ('listings', '0010_remove_pet_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='med',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical_pet_app.medical_pet'),
            preserve_default=False,
        ),
    ]
