# Generated by Django 4.1.6 on 2023-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_pet_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth:'),
        ),
    ]
