# Generated by Django 4.1.6 on 2023-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_pet_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
