# Generated by Django 4.1.6 on 2023-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.FloatField(blank=True, null=True, verbose_name='Age in weeks'),
        ),
    ]
