# Generated by Django 4.1.6 on 2023-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='profile_pictures/%Y/%m/%d'),
        ),
    ]
